version: '2.1'
services:
  traefik:
    build:
      context: ./traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
      - "80:80"

  mongo:
    image: mongo

  mongo-seed:
    build: 
      context: ./dbfixtures
      dockerfile: ./Dockerfile
    depends_on:
      - mongo

  nats:
    image: nats

  students:
    build: 
      context: .
      dockerfile: students-docker/Dockerfile
    command: ["-mongo", "mongo", "-nats", "nats://nats:4222"]
    depends_on:
      - nats
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.backend=students"
      - "traefik.frontend.rule=PathPrefix:/student"

  subjects:
    build: 
      context: .
      dockerfile: subjects-docker/Dockerfile
    command: ["-mongo", "mongo", "-nats", "nats://nats:4222"]
    depends_on:
      - nats
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.backend=subjects"
      - "traefik.frontend.rule=PathPrefix:/subject"
